In [20]:
import numpy as np

In [21]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x, y

(array([3, 4, 5]), array([4, 9, 7]))

In [22]:
x + y

array([ 7, 13, 12])

In [23]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [24]:
x.ndim

2

In [25]:
x.dtype

dtype('int64')

In [26]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [27]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [28]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [29]:
x.shape

(2, 2)

In [30]:
# Given an array x, the expression x.sum() sums all of its elements, using the sum() method for arrays.
# The call x.sum() automatically provides x as the first argument to its sum() method
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

In [31]:
# We could also sum the elements of x by passing in x as an argument to the np.sum() function
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

In [32]:
# The reshape() methor returns a new array with the same elements as x, but a different shape. We do this by passing in a tuple()
# in our call to reshape(), in this case(2, 3). This tuple specifies that we would like to create a two-dimensional array with 2 rows and 3 columns.
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [33]:
# The previous output reveals that numpy arrays are specified as a sequence of rows. This is called row-major ordering as opposed to column-major ordering.
# Python (and hence numpy) uses 0-based indexing. This means that to access the top left element of x_reshape, we type in x_reshape[0, 0]

x_reshape[0, 0]

np.int64(1)

In [34]:
x_reshape[1, 2]

np.int64(6)

In [35]:
x[2]

np.int64(3)

In [36]:
# Now let's modify the top left element of x_reshape. To our surprise, we discover that the first element of x has been modified as well!
print('x before we modify x_reshape :\n', x)
print('x_reshape before we modify x _reshape :\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element :\n', x_reshape)
print('x after we modify top left element of x_reshape :\n', x)

x before we modify x_reshape :
 [1 2 3 4 5 6]
x_reshape before we modify x _reshape :
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element :
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape :
 [5 2 3 4 5 6]


Modifying x_reshape also modified x because the two objects occupy the same space in memory.

In [37]:
# We just saw that we can modify an element of an array. Can we also modify a tuple? It turns out that we cannot, and trying to do so introduces
# an exception, or error
#my_tuple = (3, 4, 5)
#my_tuple[0] = 2

In [38]:
# We now briefly mention some attributes of arrays that will come in handy.
# An array's shape attribute contains its dimension; this is always a tuple.
# The ndim attribute yields the number of dimensions, and T provides its transpose.
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

Notice that the three individual outputs (2, 3), 2, and array ([[5, 4], [2, 5], [3, 6]]) are themselves output as a tuple.

In [39]:
# We will often want to apply functions to arrays. For instance, we can compute the square root of the entries using the np.sqrt() function
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [40]:
# We can also square the elements
x ** 2

array([25,  4,  9, 16, 25, 36])

In [41]:
# We can compute the square roots using the same notation, raising to the power of 1/2 instead of 2
x ** 0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

Throughout this book, we will often want to generate random data. The np.random.normal() function generates a vector of random normal variables.
We can learn more about this function by looking at the help page, via a call to np.random.normal?. The first line of the help page reads
normal(loc=0.0, scale=1.0, size=None). This signature line tells us that the function's arguments are loc, scale, and size. These are keyword arguments, which means that when they are passed into the function, they can be referred to by name(in any order). By default, this function will generate random normal variables(s) with mean (loc) 0 and standard deviation (scale) 1; furthermore, a single random variable will be generated unless the argument to size is changed.

In [42]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [43]:
# We now generate 50 independent random variables from a N(0, 1) distribution.
x = np.random.normal(size=50)
x

array([-0.48756388,  1.39686645, -1.94920981, -2.96794868, -0.46126935,
        0.49313878, -1.11396993, -0.05234757,  0.26329052,  1.00846048,
        0.37217089, -0.38767745,  1.12888379, -1.94459633, -2.08583775,
        0.49535508, -1.83783718, -0.03631049,  0.44257061, -0.56778946,
       -0.41803545,  0.24614135, -0.27014592, -1.147041  , -1.44481098,
        1.88386866,  0.64127516,  0.07714965,  1.34066336,  1.11177963,
       -0.91497321, -1.45083615,  0.37379534, -0.19670023,  0.49713462,
       -0.66148282,  1.06088525,  0.75070201,  0.25455593, -0.34507864,
        0.47625118,  1.1714498 , -0.23327562, -0.95671282, -1.358133  ,
       -0.86787024,  1.99177679,  1.12166418, -0.43752193,  0.81538997])

In [44]:
# We can create an array y by adding an independent N(50, 1) random variable to each element of x.
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([49.46651816, 51.91355587, 49.71190573, 47.43673969, 49.4496917 ,
       50.16652396, 50.8005797 , 50.96505818, 49.04102936, 50.77689402,
       48.52197201, 47.7864008 , 50.86244826, 50.27885012, 50.46788321,
       49.84714424, 48.94108272, 49.29849958, 50.92180013, 50.08846912,
       49.7116848 , 49.92136164, 48.05573065, 49.15853683, 49.10394891,
       52.21116771, 51.81162974, 51.10788865, 51.93900942, 50.87853567,
       49.03745793, 49.18840001, 49.50913295, 50.56048264, 49.71363625,
       51.49116079, 50.73072285, 51.26588221, 48.90919048, 49.22258061,
       50.19185672, 51.72742685, 50.51349537, 49.60088938, 47.45284287,
       48.70997052, 52.47066408, 52.29248018, 50.0291336 , 50.39014689])

In [45]:
# The np.corrcoef() function computes the correlation matrix between x and y. The off-diagonal elements give the correlation between x and y.
np.corrcoef(x, y)

array([[1.        , 0.63929724],
       [0.63929724, 1.        ]])

In [46]:
#Each time we call np.random.normal(), we will get a different answer, as shown in the following example.
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))

[10.14892685  2.16095777]
[-5.51301454 -0.60009641]


In [47]:
#In order to ensure that our code provides the same results each time it is run, we can set a random seed using the np.random.default_rng() function.
#This function takes an aritrary, user-specified interger argument.
#If we set a random seed before generating random data, then re-running our code will yield the same results. The object rng has essentially all the 
#random number generating methods found in np.random. Hence, to generate normal data we use rng.normal().
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


Throughout the labs, we use np.random.default_rng() whenever we perform calculations involving random quantities with numpy

In [48]:
# The np.mean(), np.var(), and np.std() functions can be used to compute the mean, variance, and standard deviation of arrays. These functions are
#also available as methods on the arrays.
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [49]:
np.var(y), y.var(), np.mean((y - y.mean()) ** 2)

(np.float64(2.7243406406465125),
 np.float64(2.7243406406465125),
 np.float64(2.7243406406465125))

Notice that by default np.var() divides by the sample size n rather than n - 1; see the ddof argument in np.var?

In [50]:
np.var?

Signature:      
np.var(
    a,
    axis=None,
    dtype=None,
    out=None,
    ddof=0,
    keepdims=<no value>,
    *,
    where=<no value>,
    mean=<no value>,
    correction=<no value>,
)
Call signature:  np.var(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function var at 0x000001877C63F380>
File:            c:\users\anthonny.paz\documents\github\ml-projects\ml_proj\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a
distribution.  The variance is computed for the flattened array by
default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Array containing numbers whose variance is desired.  If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the variance is computed.  The default is to
    compute the variance of th

In [51]:
np.sqrt(np.var(y)), np.std(y)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

In [52]:
# The np.mean(), np.var(), and np.std() functions can also be applied to the rows and columns of a matrix. To see this, we construct a 10 x 3 matrix of
#N(0, 1) random variables, and consider computing its row sums.
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [53]:
# Since arrays are row-major ordered, the first axis, i.e. axis = 0, refers to its rows. We pass this argument into the mean() method for the object X.
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [54]:
# The following yields the same result.
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])